volumes:
  database-data:
    driver: local

  redis-data:
    driver: local

services:
  api:
    build:
      context: .
      dockerfile: .dockerfiles/php/Dockerfile
      pull: true
    container_name: api
    tty: true
    ports:
      - 9000:9000
    volumes:
      - .:/var/www
    networks:
      - web

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - .:/var/www
      - ./.dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web

  db:
    image: mysql:8.1
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - database-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandbox
      MYSQL_USER: sandbox
      MYSQL_PASSWORD: sandbox
    networks:
      - web

  adminer:
    image: adminer:4-standalone
    container_name: adminer
    ports:
      - 9090:8080
    depends_on:
      - db
    networks:
      - web

  mail:
    image: axllent/mailpit:latest
    container_name: mail
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - web

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    networks:
      - web

networks:
  web:
    driver: bridge
